---
name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Run test suite (opa check, regal lint, opa test, pytest)
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.2.2

      - name: Set up OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Set up Regal
        run: |
          curl -L -o regal https://github.com/StyraInc/regal/releases/latest/download/regal_Linux_x86_64
          chmod +x regal
          sudo mv regal /usr/local/bin/regal

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: ./scripts/test.sh
